### PR TITLE
feat: ACryptoS StableSwap

### PR DESCRIPTION
**Pull request by aandreakis**
## Checklist:

-   [ ] Prefix PR title with `[WIP]` if necessary.
-   [ ] Add tests to cover changes as needed.
-   [ ] Update documentation as needed.
-   [ ] Add new entries to the relevant CHANGELOG.jsons.

### CODE REVIEW

**Comment by romainbutteaud** [comment]
I think we should name it `Acryptos` instead of `StableSwap` because StableSwap is the generic name of that stable  swap implementation (Curve / Shell / Saddle...) see: https://curve.fi/files/stableswap-paper.pdf

**Review by dorothy-zbornak — APPROVED** [review]
looks good! :+1: :eye: :lips: :eye: :+1:

**Comment by aandreakis** [comment]
> I think we should name it `Acryptos` instead of `StableSwap` because StableSwap is the generic name of that stable swap implementation (Curve / Shell / Saddle...) see: https://curve.fi/files/stableswap-paper.pdf

Sounds good. Renaming to `ACryptoS`.

**Review by romainbutteaud — APPROVED** [review]
🚀

**Pull request merged**
