### PR TITLE
GAEAlimited:gsc20-protocol:development >>>0xProject | Base: development

### PR DESCRIPTION
**Pull request by GAEAlimited**
## Checklist:

-   [ ] Add tests to cover changes as needed.
-   [ ] Update documentation as needed.
-   [ ] Add new entries to the relevant CHANGELOG.jsons.

### CODE REVIEW

**Review by ErnestoLara — CHANGES_REQUESTED** [review]
buena

**Review by ErnestoLara — APPROVED** [review]
l

**Review by GAEAlimited — COMMENTED** [review]
x

**Review by GAEAlimited — COMMENTED** [review]
Viewed & In Progress

**Pull request closed without merging**
